What values to put in DAGSHUB_ACCESS_KEY and DAGSHUB_SECRET_ACCESS_KEY

name: Install Dependencies and Set Up Environment

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install git
      run: |
        sudo apt-get update
        sudo apt-get install git

    - name: Install Java JDK
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install openjdk-8-jdk-headless -qq > /dev/null

    - name: Install Spark
      run: |
        wget -q https://archive.apache.org/dist/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz
        tar -xvf spark-3.5.1-bin-hadoop3.tgz

    - name: Install Python dependencies
      run: |
        pip install -q findspark
        pip install pyspark==3.5.1
        pip install dagshub
        pip install xgboost
    - name: Install DVC
      run: |
        pip install dvc

    - name: Initialize DVC
      run: |
        dvc init

    - name: Configure DVC
      run: |
        dvc remote add origin https://dagshub.com/harshitbudakotimatsc20/credit_card_fraud_ML.dvc
        dvc remote modify origin user ${{ secrets.DAGSHUB_USERNAME }}
        dvc remote modify origin password ${{ secrets.DAGSHUB_PASSWORD }}

    - name: Pull data
      run: |
        dvc pull

    - name: Clone DagsHub repository
      run: |
        git clone https://dagshub.com/harshitbudakotimatsc20/credit_card_fraud_ML.git
        cd credit_card_fraud_ML
    - name: Install s3cmd
      run: |
        sudo apt-get install s3cmd
    - name: Download and run scripts from DAGsHub Storage
      run: |
        echo "[default]" > ~/.s3cfg
        echo "access_key = ${{ secrets.DAGSHUB_USERNAME }}" >> ~/.s3cfg
        echo "secret_key = ${{ secrets.DAGSHUB_ACCESS_KEY }}" >> ~/.s3cfg
        echo "host_base = dagshub.com" >> ~/.s3cfg
        echo "host_bucket = credit_card_fraud_ML.dagshub.com" >> ~/.s3cfg
        s3cmd get s3://${{ secrets.DAGSHUB_USERNAME }}/credit_card_fraud_ML/preprocessingofdata.py
        python preprocessingofdata.py ${{ secrets.DATASET1_PATH }} ${{ secrets.DATASET2_PATH }}
        s3cmd get s3://${{ secrets.DAGSHUB_USERNAME }}/credit_card_fraud_ML/encodingoftestdata.py
        python encodingoftestdata.py ${{ secrets.DATASET3_PATH }} ${{ secrets.DATASET4_PATH }}
        s3cmd get s3://${{ secrets.DAGSHUB_USERNAME }}/credit_card_fraud_ML/model_predictions.py
        python model_predictions.py ${{ secrets.DATASET6_PATH }} ${{ secrets.DATASET7_PATH }}

      env:
        CONFIG_PATH: ${{ github.workspace }}/config.json 
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        DAGSHUB_ACCESS_KEY: ${{ secrets.DAGSHUB_ACCESS_KEY }}

    - name: Update and push files
      run: |
        dvc add s3://credit_card_fraud_ML/processed_old_data.parquet s3://credit_card_fraud_ML/processed_new_data.parquet s3://credit_card_fraud_ML/encoded_past_data.parquet s3://credit_card_fraud_ML/encoded_new_data.parquet s3://credit_card_fraud_ML/latest_predictions.parquet
        dvc commit -f
        dvc push
      env:
        MLFLOW_TRACKING_URI: https://dagshub.com/harshitbudakotimatsc20/credit_card_fraud_ML.mlflow
        MLFLOW_S3_ENDPOINT_URL: https://dagshub.com/harshitbudakotimatsc20/credit_card_fraud_ML.dvc
        DAGSHUB_ACCESS_KEY: ${{ secrets.DAGSHUB_ACCESS_KEY }}
